# This is a basic workflow to help you get started with Actions

name: Reusable WorkFlow2

on:
  workflow_call:
jobs:
  rul-jpb1:
    runs-on: ubuntu-latest
    steps:
      - name: "Prueba de mensaje de reutilizacion"
        run: |
          echo "Estoy reusando un workflow dos"
